apiVersion: v1
kind: ConfigMap
metadata:
  name: hospital-config
  labels:
    app.kubernetes.io/name: hospital-application
    app.kubernetes.io/component: config
    app.kubernetes.io/part-of: hospital-application
data:
  NODE_ENV: "production"
  PORT: "5000"
  MONGO_URI: "mongodb://hospital-mongodb:27017/hospital_management"
