apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "hospital-app.fullname" . }}-config
  labels:
    {{- include "hospital-app.labels" . | nindent 4 }}
    app.kubernetes.io/component: config
data:
  {{- range $key, $value := .Values.env }}
  {{ $key }}: {{ $value | quote }}
  {{- end }}
