{{- if .Values.secret.create }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "hospital-app.secretName" . }}
  labels:
    {{- include "hospital-app.labels" . | nindent 4 }}
    app.kubernetes.io/component: secret
type: Opaque
stringData:
  {{- range $key, $value := .Values.secret.stringData }}
  {{ $key }}: {{ $value | quote }}
  {{- end }}
{{- end }}
